name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      SPRING_PROFILES_ACTIVE: local
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build & Test
        run: ./gradlew clean build

      - name: Spotless Check
        run: ./gradlew spotlessCheck